[package]
name = "lotus3"
version = "0.1.0"
authors = ["Oleg Scherbakov <scherbakov.oleg@gmail.com>"]
edition = "2018"

[dependencies.sdl2]
version = "0.31.0"
features = ["unsafe_textures"]

[dev-dependencies]
md5 = "0.6.0"
